services:
  db:
    image: postgres:14
    container_name: nfe-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  db-test:
    image: postgres:14
    container_name: nfe-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfe_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./init-db-test.sh:/docker-entrypoint-initdb.d/init-db-test.sh

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db-test
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npx prisma migrate deploy"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nfe

volumes:
  pgdata:
  pgdata_test:
